export default {
    WP_SITE_URL: process.env.WP_SITE_URL,
    WP_USERNAME: process.env.WP_USERNAME,
    APPLICATION_PASSWORD: process.env.APPLICATION_PASSWORD,
    PRODUCTION_WP_SITE_URL: process.env.PRODUCTION_WP_SITE_URL,
    PRODUCTION_WP_USERNAME: process.env.PRODUCTION_WP_USERNAME,
    PRODUCTION_APPLICATION_PASSWORD: process.env.PRODUCTION_APPLICATION_PASSWORD
}